### ISSUE TITLE
[FEATURE] Add simple adress for shop

### ISSUE THREAD

**Issue by Younext19** [z3ddycus/tp-shop#14] opened 2024-01-20 08:59 UTC

**Comment by Ydrasil** [comment] 2024-01-20 09:13
Seems to be a duplicate of https://github.com/z3ddycus/tp-shop/issues/9

**Comment by Younext19** [comment] 2024-01-20 09:14
Yes, i didn't see that now i'm working on products wishlist

**Closed as completed** 2024-01-20 09:24 UTC
